### ISSUE TITLE
ValueError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by robbyki** [damianavila/RISE#157]
Running into below traceback after running setup.py...

```
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    main()
  File "setup.py", line 34, in main
    enable=(not args.no_enable))
  File "setup.py", line 14, in install
    cm.update('notebook', {"load_extensions": {"livereveal/main": True}})
  File "/ebs/anaconda3/lib/python3.4/site-packages/traitlets/config/manager.py", line 85, in update
    data = self.get(section_name)
  File "/ebs/anaconda3/lib/python3.4/site-packages/traitlets/config/manager.py", line 63, in get
    return json.load(f)
  File "/ebs/anaconda3/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/ebs/anaconda3/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/ebs/anaconda3/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/ebs/anaconda3/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by damianavila** [comment]
mmm... seems a problem upstream...

`traitlets` version? platform?

**Comment by robbyki** [comment]
Sorry. you are right. discovered today that for still unknown reason this is happening whenever I open a new notebook on Jupyter 4.0.6, on EC2 Centos 65 and Anaconda Py34. Not an issue with RISE; please feel free to close.

**Comment by damianavila** [comment]
Thanks for the report, closing.
