### ISSUE TITLE
Installation locations and environment variables

### ISSUE THREAD

**Issue by thpfaff** [damianavila/RISE#183]
I have installed RISE to its standard location in 
`~/.local/share/jupyter/nbextensions/livereveal/`

Now I wanted to install it to a different directory. The documentation says that this can be changed by setting the JUPYTER_CONFIG_DIR environment variable.
The [jupyter documentation](http://jupyter.readthedocs.org/en/latest/system.html) implies that the extension should probably go to the directory indicated by JUPYTER_PATH

Regardless of which variable I set, invoking `python setup.py install` produces the following error

```
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    main()
  File "setup.py", line 34, in main
    enable=(not args.no_enable))
  File "setup.py", line 10, in install
    overwrite=use_symlink, user=True)
  File "~/dev/venvs/rise/local/lib/python2.7/site-packages/notebook/nbextensions.py", line 212, in install_nbextension
    os.makedirs(dest_dir)
  File "~/dev/venvs/rise/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '~/.local/share/jupyter/nbextensions/livereveal/'
```
I am using python 2.7.3 with notebook version 4.1.0 on an Ubuntu 12.04 system.

**Comment by thpfaff** [comment]
I think, I found the problem myself.
The latest jupyter version does not use the variable JUPYTER_PATH any more but JUPYTER_DATA_DIR.
If I use this one, the installation properly goes into the right directory.
