### ISSUE TITLE
conda install error

### ISSUE THREAD

**Issue by protik77** [damianavila/RISE#238]
Hi,

I am getting the following error while installing RISE using conda.

```
conda install -c damianvila82 rise=4.0.0b1
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : C:\protix\Miniconda3  (writable)
    default environment : C:\protix\Miniconda3\envs\ptk.pmg
       envs directories : C:\protix\Miniconda3\envs
          package cache : C:\protix\Miniconda3\pkgs
           channel URLs : https://conda.anaconda.org/damianvila82/win-64
                          https://conda.anaconda.org/damianvila82/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.9 requests/2.12.4 CPython/3.5.2 Windows/10 Windows/10.0.14393



`$ C:\protix\Miniconda3\Scripts\conda-script.py install -c damianvila82 rise=4.0.0b1`




    Traceback (most recent call last):
      File "C:\protix\Miniconda3\lib\site-packages\conda\exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\protix\Miniconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\protix\Miniconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\protix\Miniconda3\lib\site-packages\conda\cli\install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\protix\Miniconda3\lib\site-packages\conda\core\index.py", line 124, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\protix\Miniconda3\lib\site-packages\conda\core\index.py", line 532, in fetch_index
        repodatas = _collect_repodatas(use_cache, tasks)
      File "C:\protix\Miniconda3\lib\site-packages\conda\core\index.py", line 521, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\protix\Miniconda3\lib\site-packages\conda\core\index.py", line 494, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\protix\Miniconda3\lib\site-packages\conda\core\index.py", line 494, in <listcomp>
        for url, schan, pri in tasks]
      File "C:\protix\Miniconda3\lib\site-packages\conda\core\index.py", line 143, in func
        res = f(*args, **kwargs)
      File "C:\protix\Miniconda3\lib\site-packages\conda\core\index.py", line 483, in fetch_repodata
        process_repodata(repodata, url, schannel, priority)
      File "C:\protix\Miniconda3\lib\site-packages\conda\core\index.py", line 410, in process_repodata
        opackages = repodata.setdefault('packages', {})
    AttributeError: 'NoneType' object has no attribute 'setdefault'
```

Any idea about how to resolve this?

Thanks.

**Comment by protik77** [comment]
Actually I misspelled the channel name. After correcting that everything worked perfectly.
