### ISSUE TITLE
Trouble installing RISE in julia (directly after a JuliaPro6.0.1 installation)

### ISSUE THREAD

**Issue by jlperla** [damianavila/RISE#316]
After installing JuliaPro 6.0.1, I followed your instructions to startup a REPL and run
```julia
using Conda
Conda.add_channel("damianavila82")
Conda.add("rise")
```

It ends up getting through almost all of the installation.  Before showing the error, I should note that the file referenced `C:\appsl\JuliaPro-0.6.0.1\pkgs-0.6.0.1\v0.6\Conda\deps\usr\pkgs\rise-5.1.0-py27_0\Scripts\.rise-post-link-script.py`  does not exist, but `"C:\appsl\JuliaPro-0.6.0.1\pkgs-0.6.0.1\v0.6\Conda\deps\usr\pkgs\rise-5.1.0-py27_0\Scripts\.rise-post-link.sh"`  does.

The error is:
```
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'damianavila82::rise-5.1.0-py27_0'.
CondaError: Cannot link a source that does not exist. C:\appsl\JuliaPro-0.6.0.1\pkgs-0.6.0.1\v0.6\Conda\deps\usr\pkgs\rise-5.1.0-py27_0\Scripts\.rise-post-link-script.py
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.

CondaError: Cannot link a source that does not exist. C:\appsl\JuliaPro-0.6.0.1\pkgs-0.6.0.1\v0.6\Conda\deps\usr\pkgs\rise-5.1.0-py27_0\Scripts\.rise-post-link-script.py
Running `conda clean --packages` may resolve your problem.

ERROR: failed process: Process(setenv(`'C:\appsl\JuliaPro-0.6.0.1\pkgs-0.6.0.1\v0.6\Conda\deps\usr\Scripts\conda.exe' install -y rise`,String["USERDOMAIN_ROAMINGPROFILE=JLPERLA-PC", "JUPYTER=C:\\appsl\\JuliaPro-0.6.0.1\\Python\\Scripts\\jupyter.exe", "HOMEPATH=\\Users\\Jesse Perla", "ProgramData=C:\\ProgramData", "ProgramW6432=C:\\Program Files", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.RB;.RBW", "SESSIONNAME=Console", "APPDATA=C:\\Users\\Jesse Perla\\AppData\\Roaming", "PUBLIC=C:\\Users\\Public", "USERDOMAIN=JLPERLA-PC", "OS=Windows_NT", "PROCESSOR_REVISION=2d07", "TMP=C:\\Users\\JESSEP~1\\AppData\\Local\\Temp", "ALLUSERSPROFILE=C:\\ProgramData", "Path=C:\\appsl\\JuliaPro-0.6.0.1\\Julia-0.6.0\\bin;C:\\Program Files\\Docker\\Docker\\Resources\\bin;C:\\apps\\Python\\Python36-32\\Scripts\\;C:\\apps\\Python\\Python36-32\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\PuTTY\\;C:\\apps\\MiKTeX 2.9\\miktex\\bin\\;C:\\apps\\MATLAB\\R2017a\\runtime\\win64;C:\\apps\\MATLAB\\R2017a\\bin;C:\\apps\\tomlab\\shared;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\apps\\Ruby22\\bin;C:\\Users\\Jesse Perla\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Jesse Perla\\AppData\\Local\\GitHubDesktop\\bin", "COMPUTERNAME=JLPERLA-PC", "USERNAME=Jesse Perla", "CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files", "CommonProgramFiles=C:\\Program Files\\Common Files", "CONDARC=C:\\appsl\\JuliaPro-0.6.0.1\\pkgs-0.6.0.1\\v0.6\\Conda\\deps\\usr\\condarc-julia.yml", "USERPROFILE=C:\\Users\\Jesse Perla", "PSModulePath=C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules", "ETK_ROOT=C:\\working\\libraries", "PROCESSOR_LEVEL=6", "GADFLY_THEME=dark", "TEMP=C:\\Users\\JESSEP~1\\AppData\\Local\\Temp", "SystemDrive=C:", "HOMEDRIVE=C:", "LOCALAPPDATA=C:\\Users\\Jesse Perla\\AppData\\Local", "PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 45 Stepping 7, GenuineIntel", "NUMBER_OF_PROCESSORS=12", "=::=::\\", "ComSpec=C:\\WINDOWS\\system32\\cmd.exe", "SystemRoot=C:\\WINDOWS", "OneDrive=C:\\Users\\Jesse Perla\\OneDrive", "TEXAUX=c:/working/texaux", "CONDA_DEFAULT_ENV=C:\\appsl\\JuliaPro-0.6.0.1\\pkgs-0.6.0.1\\v0.6\\Conda\\deps\\usr", "ProgramFiles(x86)=C:\\Program Files (x86)", "JULIA_PKGDIR=C:\\appsl\\JuliaPro-0.6.0.1\\pkgs-0.6.0.1", "OPENBLAS_NUM_THREADS=8", "LOGONSERVER=\\\\JLPERLA-PC", "CONDA_PREFIX=C:\\appsl\\JuliaPro-0.6.0.1\\pkgs-0.6.0.1\\v0.6\\Conda\\deps\\usr", "windir=C:\\WINDOWS", "FPS_BROWSER_USER_PROFILE_STRING=Default", "CommonProgramW6432=C:\\Program Files\\Common Files", "ProgramFiles=C:\\Program Files", "FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer", "PROCESSOR_ARCHITECTURE=AMD64", "OPENBLAS_MAIN_FREE=1", "ETKROOT=C:\\working\\libraries"]), ProcessExited(1)) [1]
Stacktrace:
 [1] pipeline_error(::Base.Process) at .\process.jl:682
 [2] run(::Cmd) at .\process.jl:651
 [3] add(::String) at C:\appsl\JuliaPro-0.6.0.1\pkgs-0.6.0.1\v0.6\Conda\src\Conda.jl:210
```

**Comment by damianavila** [comment]
@perla, this is probably because of #315. I have already built new packages, check this message: https://github.com/damianavila/RISE/issues/315#issuecomment-342707972

**Comment by jlperla** [comment]
@damianavila  Thanks for the response.  I am using this within JuliaPro, which doesn't seem to let me get full conda access.  Is there some variation of the
```using Conda
Conda.add_channel("damianavila82")
Conda.add("rise")
```
that would work?

**Comment by jlperla** [comment]
@damianavila I am in no rush and will wait.  Thank you so much! If you wish I can close this issue after testing it tomorrow.

**Comment by damianavila** [comment]
> If you wish I can close this issue after testing it tomorrow.

That would be great! Thanks.

**Comment by jlperla** [comment]
Works great on the /dev channel, so closing.

**Comment by damianavila** [comment]
Thanks for the info... btw, the new packages are in main right now :wink:

**Comment by jlperla** [comment]
Thanks!  I updated my work computer from your main (and tried the /dev for good measure), and (1) the installation appeared to work; (2) The "Slide Type"  from the "Cell Type" toolbar is working
... but... the “Enter/Exit Live Reveal Slideshow” button on the toolbar doesn't seem to be there.  Any ideas?

**Comment by damianavila** [comment]
Please report the output of the following commands:

`jupyter --paths`
 
and
 
`jupyter nbextension list`

Additionally, if you open the js console from your browser, what do you get in the console logs?

Thanks.

**Comment by jlperla** [comment]
For the paths:
```C:\apps\JuliaPro-0.6.1.1\Python\Scripts>jupyter --paths
config:
    C:\Users\Jesse Perla\.jupyter
    c:\apps\juliapro-0.6.1.1\python\etc\jupyter
    C:\ProgramData\jupyter
data:
    C:\Users\Jesse Perla\AppData\Roaming\jupyter
    c:\apps\juliapro-0.6.1.1\python\share\jupyter
    C:\ProgramData\jupyter
runtime:
    C:\Users\Jesse Perla\AppData\Roaming\jupyter\runtime
```
nbextension list:
```
C:\apps\JuliaPro-0.6.1.1\Python\Scripts>jupyter nbextension list
Known nbextensions:
  config dir: C:\Users\Jesse Perla\.jupyter\nbconfig
    notebook section
      jupyter-js-widgets/extension enabled
      - Validating: ok
```

Sorry, not sure how to look at console logs, but can't find any obvious files.  Do I need to turn anything on to make it happen?

**Comment by damianavila** [comment]
Well, I can not see rise in the nbextension list, can you run there:

`jupyter nbextension enable rise --py --sys-prefix`

**Comment by jlperla** [comment]
The response is
```
C:\apps\JuliaPro-0.6.1.1\Python\Scripts>jupyter nbextension enable rise --py --sys-prefix
Traceback (most recent call last):
  File "runpy.py", line 184, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\apps\JuliaPro-0.6.1.1\Python\Scripts\jupyter-nbextension.EXE\__main__.py", line 9, in <module>
  File "c:\apps\juliapro-0.6.1.1\python\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\apps\juliapro-0.6.1.1\python\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "c:\apps\juliapro-0.6.1.1\python\lib\site-packages\notebook\nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "c:\apps\juliapro-0.6.1.1\python\lib\site-packages\jupyter_core\application.py", line 256, in start
    self.subapp.start()
  File "c:\apps\juliapro-0.6.1.1\python\lib\site-packages\notebook\nbextensions.py", line 896, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "c:\apps\juliapro-0.6.1.1\python\lib\site-packages\notebook\nbextensions.py", line 872, in toggle_nbextension_python
    logger=self.log)
  File "c:\apps\juliapro-0.6.1.1\python\lib\site-packages\notebook\nbextensions.py", line 483, in enable_nbextension_python
    logger=logger)
  File "c:\apps\juliapro-0.6.1.1\python\lib\site-packages\notebook\nbextensions.py", line 380, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "c:\apps\juliapro-0.6.1.1\python\lib\site-packages\notebook\nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "c:\apps\juliapro-0.6.1.1\python\lib\site-packages\traitlets\utils\importstring.py", line 42, in import_item
    return __import__(parts[0])
ImportError: No module named 'rise'
```
Just to see the output in Julia console, here is what it says:
```
julia> Conda.add("rise")
Fetching package metadata .................
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\apps\JuliaPro-0.6.1.1\pkgs-0.6.1.1\v0.6\Conda\deps\usr:
#
rise                      5.1.0                    py27_1    damianavila82
```

**Comment by jlperla** [comment]
On a fresh installation of JuliaPro 0.6.1.1, I ended up with the same sorts of failures as before.

However, I used the `pip` instructions from https://github.com/damianavila/RISE and it seems to work perfectly fine.

**Comment by damianavila** [comment]
> However, I used the pip instructions from https://github.com/damianavila/RISE and it seems to work perfectly fine.

Well... it seems to be a problem with the conda packages? I have tested without any issues in win vm, but maybe there is some other interaction when you install inside the Julia environment... I guess I can research a little bit in that environment when I have time. Do you any place where I can go and grab information/instructions to reproduce your installation? Thanks.

**Comment by jlperla** [comment]
The environment is easy to reproduce:  fresh install of the (free, MKL version of) JuliaPro from https://shop.juliacomputing.com/Products/   on Windows 10.  I am using 0.6.1.1

The better question is whether it is worth your trouble to debug, as it is very likely issues in Julia's Conda packages.  My guess is no.  Instead, since there is a simple workaround, my suggestion is to add some text below the `If you are a Julia user, you can do this from the Julia REPL with`  code.  Something to the effect of:
If this installation does not work (e.g. the  (“Enter/Exit Live Reveal Slideshow”) button is not visible, then run the steps for the `pip` installation described below.  It is important to run this within the Jupyter setup used in the Julia installation, for example, on Windows with JuliaPro the directory is something like:  `C:\JuliaPro-0.6.1.1\Python\Scripts`

**Comment by juliohm** [comment]
I am experiencing the exact same issue with the button not showing up in Jupyter. Thank you all for sharing more details, I will try the alternative solutions.

**Comment by juliohm** [comment]
Unfortunately, none of the solutions worked for me. There is some problem with the fact that Conda (or miniconda) is installed locally in Julia on its own folder in the Julia's package directory. This folder is not read by jupyter on start up, and so the notebook.json configuration file where the add-on is listed is not loaded. Maybe this issue could be reopened?

**Comment by damianavila** [comment]
Let's reopen it for further investigation.
