### ISSUE TITLE
Can't install using conda.

### ISSUE THREAD

**Issue by munozkessler** [damianavila/RISE#349]
Been trying to install RISE with conda but get the folllowing error:

The following NEW packages will be INSTALLED:

    rise: 5.2.0-py35_0 damianavila82

Proceed ([y]/n)? y

ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'damianavila82::rise-5.2.0-py35_0'.
LinkError: post-link script failed for package damianavila82::rise-5.2.0-py35_0
running your command again with `-v` will provide additional information
location of failed script: D:\Users\Mario\Anaconda3\envs\ztdl\Scripts\.rise-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

LinkError: post-link script failed for package damianavila82::rise-5.2.0-py35_0
running your command again with `-v` will provide additional information
location of failed script: D:\Users\Mario\Anaconda3\envs\ztdl\Scripts\.rise-post-link.bat
==> script messages <==
<None>

**Comment by damianavila** [comment]
Mmm... that's weird. Can you run the `conda install` command with more verbosity (I think is `--debug`)? Maybe we can catch more info about the error...

**Comment by munozkessler** [comment]
(ztdl) D:\Dropbox\Projects\deep_learning_udemy>conda install -c damianavila82 rise --verbose
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment D:\Users\Mario\Anaconda3\envs\ztdl:

The following NEW packages will be INSTALLED:

    rise: 5.2.0-py35_0 damianavila82

Proceed ([y]/n)? y

()

===> LINKING PACKAGE: damianavila82::rise-5.2.0-py35_0 <===
  prefix=D:\Users\Mario\Anaconda3\envs\ztdl
  source=D:\Users\Mario\Anaconda3\pkgs\rise-5.2.0-py35_0


$ C:\WINDOWS\system32\cmd.exe /c D:\Users\Mario\Anaconda3\envs\ztdl\Scripts\.rise-post-link.bat
==> cwd: D:\Users\Mario\Anaconda3\envs\ztdl\Scripts <==
==> exit code: 1 <==
==> stdout <==
b'\r\n(ztdl) D:\\Users\\Mario\\Anaconda3\\envs\\ztdl\\Scripts>"D:\\Users\\Mario\\Anaconda3\\envs\\ztdl\\Scripts\\jupyter-nbextension.exe" enable rise --py --sys-prefix \r\n\r\n(ztdl) D:\\Users\\Mario\\Anaconda3\\envs\\ztdl\\Scripts>if errorlevel 1 exit 1 \r\n'
==> stderr <==
b'Traceback (most recent call last):\r\n  File "d:\\users\\mario\\anaconda3\\envs\\tensorflow\\lib\\runpy.py", line 193, in _run_module_as_main\r\n    "__main__", mod_spec)\r\n  File "d:\\users\\mario\\anaconda3\\envs\\tensorflow\\lib\\runpy.py", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File "D:\\Users\\Mario\\Anaconda3\\envs\\ztdl\\Scripts\\jupyter-nbextension.exe\\__main__.py", line 9, in <module>\r\n  File "d:\\users\\mario\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\jupyter_core\\application.py", line 267, in launch_instance\r\n    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)\r\n  File "d:\\users\\mario\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\traitlets\\config\\application.py", line 658, in launch_instance\r\n    app.start()\r\n  File "d:\\users\\mario\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\notebook\\nbextensions.py", line 969, in start\r\n    super(NBExtensionApp, self).start()\r\n  File "d:\\users\\mario\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\jupyter_core\\application.py", line 256, in start\r\n    self.subapp.start()\r\n  File "d:\\users\\mario\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\notebook\\nbextensions.py", line 877, in start\r\n    self.toggle_nbextension_python(self.extra_args[0])\r\n  File "d:\\users\\mario\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\notebook\\nbextensions.py", line 853, in toggle_nbextension_python\r\n    logger=self.log)\r\n  File "d:\\users\\mario\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\notebook\\nbextensions.py", line 459, in enable_nbextension_python\r\n    logger=logger)\r\n  File "d:\\users\\mario\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\notebook\\nbextensions.py", line 374, in _set_nbextension_state_python\r\n    m, nbexts = _get_nbextension_metadata(module)\r\n  File "d:\\users\\mario\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\notebook\\nbextensions.py", line 1140, in _get_nbextension_metadata\r\n    m = import_item(module)\r\n  File "d:\\users\\mario\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\traitlets\\utils\\importstring.py", line 42, in import_item\r\n    return __import__(parts[0])\r\nImportError: No module named \'rise\'\r\n'


An error occurred while installing package 'damianavila82::rise-5.2.0-py35_0'.
LinkError: post-link script failed for package damianavila82::rise-5.2.0-py35_0
running your command again with `-v` will provide additional information
location of failed script: D:\Users\Mario\Anaconda3\envs\ztdl\Scripts\.rise-post-link.bat
==> script messages <==
<None>

Attempting to roll back.


===> REVERSING PACKAGE LINK: damianavila82::rise-5.2.0-py35_0 <===
  prefix=D:\Users\Mario\Anaconda3\envs\ztdl


An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.25
       conda is private : False
      conda-env version : 4.3.25
    conda-build version : 2.0.2
         python version : 3.5.3.final.0
       requests version : 2.13.0
       root environment : D:\Users\Mario\Anaconda3  (writable)
    default environment : D:\Users\Mario\Anaconda3\envs\ztdl
       envs directories : D:\Users\Mario\Anaconda3\envs
                          C:\Users\Mario\AppData\Local\conda\conda\envs
                          C:\Users\Mario\.conda\envs
          package cache : D:\Users\Mario\Anaconda3\pkgs
                          C:\Users\Mario\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/damianavila82/win-64
                          https://conda.anaconda.org/damianavila82/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.25 requests/2.13.0 CPython/3.5.3 Windows/10 Windows/10.0.16299
          administrator : False

`$ D:\Users\Mario\Anaconda3\Scripts\conda-script.py install -c damianavila82 rise --verbose`




    Traceback (most recent call last):
      File "D:\Users\Mario\Anaconda3\lib\site-packages\conda\core\link.py", line 497, in run_script
        subprocess_call(command_args, env=env, path=dirname(path))
      File "D:\Users\Mario\Anaconda3\lib\site-packages\conda\gateways\subprocess.py", line 56, in subprocess_call
        output=_format_output(command_str, path, rc, stdout, stderr))
    subprocess.CalledProcessError: Command '['C:\\WINDOWS\\system32\\cmd.exe', '/c', 'D:\\Users\\Mario\\Anaconda3\\envs\\ztdl\\Scripts\\.rise-post-link.bat']' returned non-zero exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Users\Mario\Anaconda3\lib\site-packages\conda\core\link.py", line 327, in _execute_actions
        run_script(target_prefix, Dist(pkg_data), 'post-unlink' if is_unlink else 'post-link')
      File "D:\Users\Mario\Anaconda3\lib\site-packages\conda\core\link.py", line 513, in run_script
        raise LinkError(message)
    conda.exceptions.LinkError: post-link script failed for package damianavila82::rise-5.2.0-py35_0
    running your command again with `-v` will provide additional information
    location of failed script: D:\Users\Mario\Anaconda3\envs\ztdl\Scripts\.rise-post-link.bat
    ==> script messages <==
    <None>


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Users\Mario\Anaconda3\lib\site-packages\conda\core\link.py", line 281, in execute
        pkg_data, actions)
      File "D:\Users\Mario\Anaconda3\lib\site-packages\conda\core\link.py", line 344, in _execute_actions
        reverse_excs,
    conda.CondaMultiError: post-link script failed for package damianavila82::rise-5.2.0-py35_0
    running your command again with `-v` will provide additional information
    location of failed script: D:\Users\Mario\Anaconda3\envs\ztdl\Scripts\.rise-post-link.bat
    ==> script messages <==
    <None>



    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Users\Mario\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "D:\Users\Mario\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "D:\Users\Mario\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "D:\Users\Mario\Anaconda3\lib\site-packages\conda\cli\install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "D:\Users\Mario\Anaconda3\lib\site-packages\conda\plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "D:\Users\Mario\Anaconda3\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "D:\Users\Mario\Anaconda3\lib\site-packages\conda\instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "D:\Users\Mario\Anaconda3\lib\site-packages\conda\core\link.py", line 297, in execute
        rollback_excs,
    conda.CondaMultiError: post-link script failed for package damianavila82::rise-5.2.0-py35_0
    running your command again with `-v` will provide additional information
    location of failed script: D:\Users\Mario\Anaconda3\envs\ztdl\Scripts\.rise-post-link.bat

**Comment by damianavila** [comment]
> ImportError: No module named 'rise'\r\n'

Maybe some mystery in the win newlines? I never saw this behavior before on my testing win box.
@kalefranz any ideas about this?

Btw, I saw you are using conda 4.3, do you see the same behavior if you use conda 4.4?

In the meantime, you can install RISE using pip, step 2 in this link: https://damianavila.github.io/RISE/installation.html

**Comment by kalefranz** [comment]
I don't think it has anything to do with the line endings.  It looks like there's some type of interaction between two different environments here...

* `d:\users\mario\anaconda3\envs\tensorflow`
* `D:\Users\Mario\Anaconda3\envs\ztdl`
