### ISSUE TITLE
Installation (5.4.1) fail on jupyter-nbextension

### ISSUE THREAD

**Issue by MikeBirdsall** [damianavila/RISE#428]
I'm getting an error on the Jupyter-nbextension install rise --py --sys-prefix command. The error is:
PermissionError: [Errno 13] Permission denied: '/usr/share/jupyter'

That directory doesn't exist. I do have the directory '/usr/local/share/jupyter'

 The full traceback (username redacted) is:
Could not figure out RISE version - using 0.0.0 (package.json not found)
Installing /home/-----/.local/lib/python3.5/site-packages/rise/static -> rise
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 716, in start
    self.install_extensions()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 695, in install_extensions
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 225, in install_nbextension_python
    destination=dest, logger=logger
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 126, in install_nbextension
    ensure_dir_exists(nbext)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/share/jupyter'

I used pip to install, the full command was:
python3 -m pip install --user RISE

**Comment by jdestefani** [comment]
I have a similar problem, where the installation fails due to a ```ModuleNotFoundError```.
Here is the full error trace:
```
PS C:\Users\jdestefani> jupyter-nbextension install rise --py --sys-prefix                                            
Traceback (most recent call last):                                                                                    
  File "D:\ProgramData\Anaconda3\Scripts\jupyter-nbextension-script.py", line 5, in <module>                          
    sys.exit(notebook.nbextensions.main())                                                                            
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance         
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)                                                
  File "D:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance     
    app.start()                                                                                                       
  File "D:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 900, in start                      
    super(NBExtensionApp, self).start()                                                                               
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_core\application.py", line 256, in start                   
    self.subapp.start()                                                                                               
  File "D:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 678, in start                      
    self.install_extensions()                                                                                         
  File "D:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 657, in install_extensions         
    **kwargs                                                                                                          
  File "D:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 211, in install_nbextension_python 
    m, nbexts = _get_nbextension_metadata(module)                                                                     
  File "D:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 1034, in _get_nbextension_metadata 
    m = import_item(module)                                                                                           
  File "D:\ProgramData\Anaconda3\lib\site-packages\traitlets\utils\importstring.py", line 42, in import_item          
    return __import__(parts[0])                                                                                       
ModuleNotFoundError: No module named 'rise'                                                                           
```

I am running Python 3.5.2, Jupyter 4.4.0, Jupyter Notebook 5.7.0 on Windows 10.

If I try to ```import rise``` from a Python prompt, I obtain the following result:
```>>> import rise
Could not figure out RISE version - using 0.0.0 (package.json not found)
>>> rise.__version__
'0.0.0'
>>>
```
Could you give me some pointers on how to solve this issue?

**Comment by jdestefani** [comment]
Indeed, no development installation. 
I installed from pip (version 18.0) using ```python -m pip install RISE```.

**Comment by damianavila** [comment]
OK, will try to reproduce as soon as I can. Thanks for the additional info.

**Comment by MikeBirdsall** [comment]
Yes, I installed from pip, using python3 -m pip install --user RISE.

I wonder if it has to do with how jupyter is installed. I don't have the directory /usr/share/jupyter, but I do have /usr/local/share/jupyter

**Comment by MikeBirdsall** [comment]
Sorry, didn't mean to close

**Comment by coltongrainger** [comment]
The following commands installed for me from the RISE directory after cloning from git

```
sudo python3 setup.py install
sudo jupyter-nbextension install rise --py --sys-prefix
sudo jupyter nbextension enable rise --py --sys-prefix
```

**Comment by englianhu** [comment]
```diff
~$ jupyter-nbextension install rise --py --sys-prefix
Installing /home/englianhu/.local/lib/python3.8/site-packages/rise/static -> rise
Making directory: /usr/share/jupyter/nbextensions/rise/
Traceback (most recent call last):
  File "/home/englianhu/.local/bin/jupyter-nbextension", line 8, in <module>
    sys.exit(main())
  File "/home/englianhu/.local/lib/python3.8/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/englianhu/.local/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/home/englianhu/.local/lib/python3.8/site-packages/notebook/nbextensions.py", line 980, in start
    super().start()
  File "/home/englianhu/.local/lib/python3.8/site-packages/jupyter_core/application.py", line 243, in start
    self.subapp.start()
  File "/home/englianhu/.local/lib/python3.8/site-packages/notebook/nbextensions.py", line 708, in start
    self.install_extensions()
  File "/home/englianhu/.local/lib/python3.8/site-packages/notebook/nbextensions.py", line 679, in install_extensions
    full_dests = install(self.extra_args[0],
  File "/home/englianhu/.local/lib/python3.8/site-packages/notebook/nbextensions.py", line 214, in install_nbextension_python
    full_dest = install_nbextension(
  File "/home/englianhu/.local/lib/python3.8/site-packages/notebook/nbextensions.py", line 184, in install_nbextension
    os.makedirs(dest_dir)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
- PermissionError: [Errno 13] Permission denied: '/usr/share/jupyter/nbextensions/rise/
```
Here I tried to surf over and get the path as I installed the anaconda which includes jupyter, just copied but still error
```r
~$ ls /usr/share/jupyter/nbextensions
jupyter-js-widgets
~$ ls /home/englianhu/anaconda3/share/jupyter/nbextensions
jupyter-js-widgets  rsconnect_jupyter
~$ sudo cp -R /home/englianhu/anaconda3/share/jupyter/ /usr/local/share/jupyter/
~$ sudo cp -R /home/englianhu/anaconda3/share/jupyter/ /usr/share/jupyter/
```
I initially install jupyter, abd than anaconda3 and  miniconda3 caused the path messy, how to modify or reinstall?

**Comment by parmentelat** [comment]
you should probably just drop the `--sys-prefix` option that specifically asks to write into the system area
