### ISSUE TITLE
Present a remote notebook

### ISSUE THREAD

**Issue by DavidNemeskey** [damianavila/RISE#432]
Is it possible to present a notebook that is running on a remote server? When I activate rise (Alt-r), it gives me the following exception:
```
ERROR:tornado.application:Exception in callback (<zmq.sugar.socket.Socket object at 0x7fe805e93a70>, <function wrap.<locals>.null_wrapper at 0x7fe805e90d90>)
Traceback (most recent call last):
  File "<venv_dir>/local/lib/python3.5/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "<venv_dir>/local/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "<venv_dir>/local/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "<venv_dir>/local/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "<venv_dir>/local/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "<venv_dir>/local/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "<venv_dir>/local/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "<venv_dir>/local/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 226, in dispatch_shell
    self.pre_handler_hook()
  File "<venv_dir>/local/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 241, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "/usr/lib/python3.5/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

**Comment by DavidNemeskey** [comment]
pip update all solved everything.
