### ISSUE TITLE
Running "jupyter labextension link ." command show error "JupyterLab failed to build"

### ISSUE THREAD

**Issue by CannotTell** [damianavila/RISE#578]
MAC OS 
Jupyterlab == 2.2.9

```bash
Yarn configuration loaded.
> /usr/local/bin/npm pack /Users/x/Desktop/main-root/RISE-jupyterlab_extension/lab

> /usr/local/bin/npm pack /Users/x/Desktop/main-root/RISE-jupyterlab_extension/lab

> rise-jupyterlab@0.1.0 prepare /Users/x/Desktop/main-root/RISE-jupyterlab_extension/lab
> jlpm run clean && jlpm run build

yarn run v1.21.1
$ rimraf lib tsconfig.tsbuildinfo
Done in 0.32s.
yarn run v1.21.1
$ tsc
Done in 5.46s.
npm notice 
npm notice 📦  rise-jupyterlab@0.1.0
npm notice === Tarball Contents === 
npm notice 0     style/index.css                      
npm notice 41B   style/rise.css                       
npm notice 4.8kB lib/index.js                         
npm notice 1.5kB package.json                         
npm notice 1.3kB README.md                            
npm notice 420B  style/icons/assessment.svg           
npm notice 499B  style/icons/insert_chart_outlined.svg
npm notice 125B  src/custom.d.ts                      
npm notice 763B  lib/index.d.ts                       
npm notice === Tarball Details === 
npm notice name:          rise-jupyterlab                         
npm notice version:       0.1.0                                   
npm notice filename:      rise-jupyterlab-0.1.0.tgz               
npm notice package size:  3.3 kB                                  
npm notice unpacked size: 9.5 kB                                  
npm notice shasum:        91aa61180356961029ba79dd2415f96d99005b7b
npm notice integrity:     sha512-OOhTXSvnkJQAK[...]Wnuxz0Qb712Hg==
npm notice total files:   9                                       
npm notice 
rise-jupyterlab-0.1.0.tgz

Node v14.10.1




> /usr/local/bin/npm pack /Users/x/Desktop/main-root/RISE-jupyterlab_extension/lab

> rise-jupyterlab@0.1.0 prepare /Users/x/Desktop/main-root/RISE-jupyterlab_extension/lab
> jlpm run clean && jlpm run build

yarn run v1.21.1
$ rimraf lib tsconfig.tsbuildinfo
Done in 0.31s.
yarn run v1.21.1
$ tsc
Done in 5.66s.
npm notice 
npm notice 📦  rise-jupyterlab@0.1.0
npm notice === Tarball Contents === 
npm notice 0     style/index.css                      
npm notice 41B   style/rise.css                       
npm notice 4.8kB lib/index.js                         
npm notice 1.5kB package.json                         
npm notice 1.3kB README.md                            
npm notice 420B  style/icons/assessment.svg           
npm notice 499B  style/icons/insert_chart_outlined.svg
npm notice 125B  src/custom.d.ts                      
npm notice 763B  lib/index.d.ts                       
npm notice === Tarball Details === 
npm notice name:          rise-jupyterlab                         
npm notice version:       0.1.0                                   
npm notice filename:      rise-jupyterlab-0.1.0.tgz               
npm notice package size:  3.3 kB                                  
npm notice unpacked size: 9.5 kB                                  
npm notice shasum:        91aa61180356961029ba79dd2415f96d99005b7b
npm notice integrity:     sha512-OOhTXSvnkJQAK[...]Wnuxz0Qb712Hg==
npm notice total files:   9                                       
npm notice 
rise-jupyterlab-0.1.0.tgz

> /usr/local/bin/npm pack /Users/x/Desktop/main-root/RISE-jupyterlab_extension/rise-reveal
npm notice 
npm notice 📦  rise-reveal@390.0.1
npm notice === Tarball Contents === 
npm notice 1.6kB package.json
npm notice 361B  README.md   
npm notice === Tarball Details === 
npm notice name:          rise-reveal                             
npm notice version:       390.0.1                                 
npm notice filename:      rise-reveal-390.0.1.tgz                 
npm notice package size:  917 B                                   
npm notice unpacked size: 1.9 kB                                  
npm notice shasum:        c4518e664f40c519662f20fcca1af4879756f814
npm notice integrity:     sha512-b9HMXDXNHXbJ9[...]7BdAXa5uC/Skg==
npm notice total files:   2                                       
npm notice 
rise-reveal-390.0.1.tgz

> node /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > @lumino/coreutils@1.5.3" has unmet peer dependency "crypto@1.0.1".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 60.43s.

> node /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 1.85s.

> node /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:dev:minimize
yarn run v1.21.1
$ jlpm run build:dev
$ jlpm run build
$ webpack
ModuleNotFoundError: Module not found: Error: Can't resolve 'rise-reveal/export/reveal.js' in '/Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/rise-jupyterlab/lib'
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:925:10
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/neo-async/async.js:2830:7
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/neo-async/async.js:6877:13
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/forEachBail.js:30:14
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
resolve 'rise-reveal/export/reveal.js' in '/Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/rise-jupyterlab/lib'
  Parsed request is a module
  using description file: /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/rise-jupyterlab/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/rise-jupyterlab/lib/node_modules doesn't exist or is not a directory
      /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/rise-jupyterlab/node_modules doesn't exist or is not a directory
      /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/node_modules doesn't exist or is not a directory
      /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/node_modules doesn't exist or is not a directory
      /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/node_modules doesn't exist or is not a directory
      /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/node_modules doesn't exist or is not a directory
      /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/node_modules doesn't exist or is not a directory
      /Users/x/.pyenv/versions/3.7.8/envs/node_modules doesn't exist or is not a directory
      /Users/x/.pyenv/versions/3.7.8/node_modules doesn't exist or is not a directory
      /Users/x/.pyenv/versions/node_modules doesn't exist or is not a directory
      /Users/x/.pyenv/node_modules doesn't exist or is not a directory
      /Users/x/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules
        using description file: /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/rise-reveal/package.json (relative path: ./export/reveal.js)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/rise-reveal/export/reveal.js doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/rise-reveal/export/reveal.js.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/rise-reveal/export/reveal.js.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/rise-reveal/export/reveal.js.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/rise-reveal/export/reveal.js.json doesn't exist
            as directory
              /Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/share/jupyter/lab/staging/node_modules/rise-reveal/export/reveal.js doesn't exist
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "/Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/lib/python3.7/site-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

  File "/Users/x/.pyenv/versions/3.7.8/envs/jupyterlab/lib/python3.7/site-packages/jupyterlab/commands.py", line 661, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter

```

**Comment by damianavila** [comment]
@CannotTell, RISE is not yet compatible with JupyterLab. This is WIP.
Did you try installing the branch living at https://github.com/damianavila/RISE/pull/381
Just curious about how you ended up with that traceback.

**Comment by CannotTell** [comment]
> @CannotTell, RISE is not yet compatible with JupyterLab. This is WIP.
> Did you try installing the branch living at #381
> Just curious about how you ended up with that traceback.

Thank you for the reply and doing this great labextension, I've already build jupyterlab-rise in jupyterlab , and it's worked. 
I saw the issues/problems youtube video on your channel and very looking forward this labextension.
